[package]
name = "qpropertyeditor"
version = "0.3.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.4.1"
convert_case = "0.8"
slint = "1.10.0"
