[package]
name = "qpropertyeditor"
version = "0.5.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.4.1"
slint = { version = "1.13", features = ["renderer-skia"] }
heck = "0.5"